### ISSUE TITLE
getUserInfo issue with keycloak

### ISSUE THREAD

**Issue by af6140** [switch-ch/meteor-accounts-oidc#1]
response = HTTP.get(
      serverUserinfoEndpoint,
      {
        headers: {
          "User-Agent": userAgent
        },
        params: {
          access_token: accessToken
        }
      }
    );

Here access token is passed as request parameters, some oidc server like keycloak seems having issue with it, changes it to use Authentication Bearer header works.

**Comment by af6140** [comment]
From the code:
https://github.com/keycloak/keycloak/blob/master/services/src/main/java/org/keycloak/protocol/oidc/endpoints/UserInfoEndpoint.java

For http get request, only get the token from header, not from request parameter.

**Comment by af6140** [comment]
According to spec http://openid.net/specs/openid-connect-core-1_0.html#UserInfo,

when http GET is used, it's recommended to pass access token with auth header.

**Comment by valerytschopp** [comment]
Feel free to open a pull request with you change.

**Comment by af6140** [comment]
cool, i submitted a pull request.

Can we do another patch release after it's been merged?

**Comment by af6140** [comment]
Yes, both GET and POST are supported, if u prefer GET i can submit another pull request.

**Comment by valerytschopp** [comment]
Yeap I would prefer to keep the GET request

**Comment by af6140** [comment]
ok, i submitted a new pull request.

**Comment by valerytschopp** [comment]
Your pull req #4 is merged.

**Comment by af6140** [comment]
cool, can we push to atmosphere?

**Comment by valerytschopp** [comment]
I've pushed the switch:oidc package v1.0.3 to Atmosphere
