### ISSUE TITLE
Handle unavailable UserInfo endpoint

### ISSUE THREAD

**Issue by marcosterland** [switch-ch/meteor-accounts-oidc#10]
Hi,
currently [Dex](https://github.com/coreos/dex/) doesn't provide a `UserInfo` URL. But it is also not mandatory according to [OpenID specifications](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata).
Consequently, the package crashes [here](https://github.com/switch-ch/meteor-accounts-oidc/blob/master/packages/switch:oidc/oidc_server.js#L101), when trying to get the `UserInfo`.

Is there a way to configure the package, such that it doesn't query the `UserInfo`?
Cheers!

**Comment by valerytschopp** [comment]
No sorry, the `UserInfo` is required to retrieve the information needed to populate the `serviceData` in https://github.com/switch-ch/meteor-accounts-oidc/blob/master/packages/switch:oidc/oidc_server.js#L16-L20

**Comment by Gimly** [comment]
Please re-open this issue, a lot of identity provider do not implement the userinfo endpoint as, as correctly explained by @marcosterland, it is only marked as Recommended in the OpenID specifications.

This means that this library doesn't work for a lot of identity providers (Azure AD B2C is another example).

Moreover, it's overkill to do a round trip to the server when all the information is already contained by default in the access token itself. You would just need to decrypt the access_token to get those information.

**Comment by valerytschopp** [comment]
Hi @Gimly 
Feel free to propose a fix/modification for this issue

**Comment by Gimly** [comment]
Hi @valerytschopp, here you go 😄, juste created a pull request. Seems to be working correctly with both Azure B2C and Keycloak (two IdP that I could test on).

Please comment the pull request if you want me to change something.
