### ISSUE TITLE
can we publish a new version include the idTokenWhitelsitFields feature to atomosphere

### ISSUE THREAD

**Issue by af6140** [switch-ch/meteor-accounts-oidc#7]

**Comment by valerytschopp** [comment]
Published switch:oidc@1.0.4.                  
Published switch:accounts-oidc@1.0.5.

**Comment by valerytschopp** [comment]
The last version of the packages `switch:oidc` v1.0.4 and `switch:account-oidc` v1.0.5 have been published in Atmosphere:

* https://atmospherejs.com/switch/oidc
* https://atmospherejs.com/switch/accounts-oidc
